# Generated by Django 4.2.5 on 2023-09-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_schedule_user_delete_workingschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="cloudId",
            field=models.ForeignKey(
                db_column="cloudId",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.user",
            ),
            preserve_default=False,
        ),
    ]
