# Generated by Django 4.2.5 on 2023-09-08 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_schedule_cloudid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="cloudId",
            new_name="userId",
        ),
    ]
