# Generated by Django 4.2.5 on 2023-09-08 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_rename_cloudid_schedule_userid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="userId",
            new_name="cloudId",
        ),
    ]
