# Generated by Django 4.2.5 on 2023-09-17 17:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0005_rename_userid_schedule_cloudid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="daysOfWeek",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="endDate",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="endTime",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="isRecurring",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="startDate",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="startTime",
        ),
        migrations.AddField(
            model_name="schedule",
            name="byweekday",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="dtstart",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="freq",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
