# Generated by Django 4.2.5 on 2023-09-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "schedule",
            "0006_remove_schedule_daysofweek_remove_schedule_enddate_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="cloudId",
        ),
        migrations.AddField(
            model_name="schedule",
            name="userId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.user",
            ),
            preserve_default=False,
        ),
    ]
