# Generated by Django 4.2.5 on 2023-09-17 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0007_remove_schedule_cloudid_schedule_userid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="userId",
            new_name="user",
        ),
    ]
